In [1]:
import numpy
import torch

In [6]:
t = torch.tensor([[1, 2], [3, 4.]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [7]:
t = torch.tensor([[1, 2], [3, 4.]], device="cuda:0")
print(t)

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')


In [8]:
t = torch.tensor([[1, 2], [3, 4.]], dtype=torch.float64)
print(t)

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [9]:
t = torch.arange(0, 10)
print(t)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [12]:
t = torch.zeros(100, 10).to("cuda:0")
print(t)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],


In [13]:
t = torch.randn(100, 10)
print(t)

tensor([[ 6.0992e-01, -2.9478e-01, -3.4758e-01,  5.2860e-01,  1.5715e+00,
          1.3306e+00, -1.5556e+00,  1.5549e+00, -1.0594e+00,  8.5652e-01],
        [ 1.4278e+00,  7.9935e-01,  1.7507e-01,  1.0386e+00,  7.2336e-01,
          2.6328e-01,  9.5473e-01,  1.2246e+00,  1.9677e+00,  9.1524e-01],
        [-8.9448e-01, -6.5089e-01, -3.7380e-01, -4.0460e-02,  7.6163e-01,
          1.3480e+00,  2.6299e-01, -2.6953e-01, -1.2643e+00, -1.6227e+00],
        [ 7.7153e-01,  2.8369e-01, -6.4127e-01, -3.1046e-01,  1.3771e+00,
         -1.0124e+00, -4.1780e-01,  1.2797e-01,  9.3388e-01, -5.5631e-01],
        [-1.1316e+00,  6.5335e-01, -6.2322e-01, -3.3210e-01,  5.5930e-01,
          1.3350e+00, -7.6007e-01, -8.4322e-01,  1.0947e-01,  2.5012e-01],
        [-5.1724e-01,  3.6075e-01,  1.1656e+00, -1.4106e+00,  1.2113e-01,
         -1.7327e+00, -6.0742e-01, -9.0420e-01,  5.6725e-01,  6.4838e-01],
        [ 9.5187e-01,  2.2666e-01, -3.4833e-01, -8.0784e-03, -6.2067e-01,
          1.7667e-01, -6.4868e-0

In [14]:
t.size()

torch.Size([100, 10])

In [18]:
# numpyメソッドを使用してndarrayに変換
t = torch.tensor([[1, 2], [3, 4.]])
x = t.numpy()
print(t.dtype)
print(x.dtype)

torch.float32
float32


In [19]:
t = torch.tensor([[1, 2], [3, 4]], device="cuda:0")
x = t.to("cpu").numpy()
print(t)
print(x)

tensor([[1, 2],
        [3, 4]], device='cuda:0')
[[1 2]
 [3 4]]


In [21]:
# Tensorのインデクシング操作例
t = torch.tensor([[1, 2, 3], [4, 5, 6.]])
print(t[0, 2])
print(t[:, :2])
print(t[:, [1, 2]])
print(t[t > 3])
t[0, 1] = 100
print(t)
t[:, 1] = 200
print(t)
t[t > 10] = 20
print(t)

tensor(3.)
tensor([[1., 2.],
        [4., 5.]])
tensor([[2., 3.],
        [5., 6.]])
tensor([4., 5., 6.])
tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])
tensor([[  1., 200.,   3.],
        [  4., 200.,   6.]])
tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])


In [ ]:
v = torch.tensor([1, 2, 3.])
w = torch.tensor([0, 10, 20.])
m = torch.tensor([[0, 1, 2], [100, 200, 300.]])
v2 = v + 10
print("v2 : ", v2)
v3 = v ** 2
print("v2 : ", v3)
z = v - w
print(z)
u = 2 * v - w / 10 + 6.0
print(u)
m2 = m * 2.0
print(m2)
m3 = m + v
m4 = m + m
print(m3)
print(m4)

v2 :  tensor([11., 12., 13.])
v2 :  tensor([1., 4., 9.])
tensor([  1.,  -8., -17.])
tensor([ 8.,  9., 10.])
tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])
tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])
tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])


In [28]:
# 100 × 10のテストデータを用意
X = torch.randn(100, 10)
print(X)
# 数学関数を含めた数式
y = X * 2 + torch.abs(X)
print("y : ", y)
# 平均値を求める
m = torch.mean(X)
print("平均値 : ", m)
# 関数ではなくメソッドとしても利用可能
m = X.mean()
print(m)
# 集計結果は0次元のtensorでitemメソッドを使用して値を取り出すことができる
m_value = m.item()
print("m_value : ", m_value)
#集計は次元を指定できる。以下は行方向に集計して列ごとに平均値を計算している
m2 = X.mean(0)
print("m2 : ", m2)

tensor([[-1.4691e-01,  1.6540e-01,  1.8802e+00,  5.4439e-01, -1.2398e-01,
          1.7243e-01,  1.1758e-01, -6.9793e-01,  5.5587e-01,  1.2274e+00],
        [-1.5528e+00, -1.2487e+00, -4.1042e-01, -2.9691e-01, -1.4946e+00,
          8.6456e-02,  1.4006e+00, -9.6378e-01,  9.6502e-01,  1.0102e-01],
        [-1.5636e+00,  1.3705e+00, -2.6475e-01, -9.3692e-03, -9.6237e-01,
          4.9602e-01,  1.1647e+00,  5.1176e-01,  1.1097e+00,  1.2616e-02],
        [ 3.4726e-01, -9.8000e-01,  5.4731e-01, -1.0268e+00, -8.3566e-01,
         -2.1525e+00,  1.1296e-01,  4.7297e-01,  6.5392e-01,  8.6100e-01],
        [ 9.6284e-02,  4.0399e-01, -1.1226e-01, -2.7184e-01,  1.2549e+00,
         -4.8915e-01, -1.7106e+00,  4.9668e-01, -1.0553e+00,  2.3210e-01],
        [ 1.0619e+00, -4.1702e-01, -8.8131e-01, -4.9722e-01, -6.1927e-01,
         -9.1216e-02, -5.6639e-01,  1.0149e+00, -1.5981e+00,  1.8132e+00],
        [-3.7677e-01, -8.6874e-01,  1.4058e-01,  2.1181e-01, -1.0079e-01,
          1.0998e+00,  2.2982e-0

In [33]:
x1 = torch.tensor([[1, 2], [3, 4.]])
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]])
print(x1)
print(x1.view(4, 1))
print(x1.view(1, -1))
print("転置 :", x2.t())
print(torch.cat([x1, x2], dim=1))
hwc_img_data = torch.rand(100, 64, 32, 3)
chw_img_data = hwc_img_data.transpose(1, 2).transpose(1, 3)
print(hwc_img_data)
print(chw_img_data)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.],
        [3.],
        [4.]])
tensor([[1., 2., 3., 4.]])
転置 : tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])
tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])
tensor([[[[0.4263, 0.7953, 0.3651],
          [0.0826, 0.8826, 0.4214],
          [0.1332, 0.8144, 0.3686],
          ...,
          [0.6064, 0.9930, 0.7071],
          [0.8025, 0.2379, 0.4093],
          [0.4137, 0.4609, 0.2911]],

         [[0.1751, 0.3943, 0.6951],
          [0.9122, 0.3546, 0.0960],
          [0.1067, 0.0771, 0.2735],
          ...,
          [0.2605, 0.8518, 0.4615],
          [0.6249, 0.0173, 0.2622],
          [0.2541, 0.2048, 0.5165]],

         [[0.1204, 0.1760, 0.5487],
          [0.7853, 0.1150, 0.8369],
          [0.0329, 0.9746, 0.1067],
          ...,
          [0.4543, 0.3372, 0.0297],
          [0.5382, 0.7182, 0.3026],
          [0.9185, 0.7616, 0.9539]],

         ...,

         [[0.7841, 0.2580, 0