In [1]:
import numpy as np

In [4]:
w = np.array([[5.0], [3.0]])
x = np.array([[1.0, 5.0]])
xw = np.matmul(x, w)
ww = np.matmul(w.T, w)

print(f"xとwの内積) 形:{xw.shape}, 型:{xw.dtype}\n{xw}\n")
print(f"wのノルム) 形:{ww.shape}, 型:{ww.dtype}\n{ww}\n")

xとwの内積) 形:(1, 1), 型:float64
[[20.]]

wのノルム) 形:(1, 1), 型:float64
[[34.]]



In [6]:
# x[i-1, :] → 各データ
# x[:, j-1] → 一つのパラメータ
X = np.array([[1.0, 2.0], [2.0, 4.0], [3.0, 6.0]])
Xrow1 = X[[0], :]
Xcol2 = X[:, [1]]
print(f"行列X) 形:{X.shape}, 型:{X.dtype}, {X}")
print(f"1行目) 形:{Xrow1.shape}, 型:{Xrow1.shape}, {Xrow1}")
print(f"2列目) 形:{Xcol2.shape}, 形:{Xcol2.dtype}, {Xcol2}")

行列X) 形:(3, 2), 型:float64, [[1. 2.]
 [2. 4.]
 [3. 6.]]
1行目) 形:(1, 2), 型:(1, 2), [[1. 2.]]
2列目) 形:(3, 1), 形:float64, [[2.]
 [4.]
 [6.]]


In [7]:
X[0, :]

array([1., 2.])

In [ ]:
X[[0], :] #行列の形を保持

array([[1., 2.]])

In [9]:
X = np.array([[1.0, 2.0], [2.0, 4.0], [3.0, 6.0]])
w = np.array([[5.0], [3.0]])
b = np.array([[1.0], [1.0], [1.0]])
res = np.matmul(X, w) + b
print(f"積和の結果) \n{res}")

積和の結果) 
[[12.]
 [23.]
 [34.]]


In [10]:
A = np.array([[6.0, 2.0], [2.0, 5.0]])
B = np.array([[6.0, 3.0], [2.0, 1.0]])
rankA = np.linalg.matrix_rank(A)
rankB = np.linalg.matrix_rank(B)
print(f"rankA :{rankA}")
print(f"rankB :{rankB}")

rankA :2
rankB :1


In [ ]:
if rankA == len(A):
    invA = np.linalg.inv(A)
    print(f"行列A) ランク:{rankA}, 逆行列 :{invA}")
else:
    print(f"行列A) ランク :{rankA}, 特異行列")

if rankB == len(B):
    invB = np.linalg.inv(B) #逆行列
    print(f"行列B) ランク:{rankB}, 逆行列 :{invB}")
else:
    print(f"行列B) ランク :{rankB}, 特異行列")
    

行列A) ランク:2, 逆行列 :[[ 0.19230769 -0.07692308]
 [-0.07692308  0.23076923]]
行列B) ランク :1, 特異行列


In [13]:
detA = np.linalg.det(A)
detB = np.linalg.det(B)
print(f"行列Aの行列式:{detA:.1f}")
print(f"行列Bの行列式:{detB:.1f}")

行列Aの行列式:26.0
行列Bの行列式:0.0


In [14]:
A = np.array([[3, 2], [4,1]])
L, V = np.linalg.eig(A)
print(f"固有値:{L}")
print(f"固有ベクトル:{V}")

固有値:[ 5. -1.]
固有ベクトル:[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [19]:
A = np.array([[3, 1], [1, 3]])
L, V = np.linalg.eig(A)
print(f"行列Aの固有値:{L}")
print(f"行列Aの固有ベクトル:{V}")
print(f"固有ベクトルの内積:{np.matmul(V[:, [0]].T, V[:, [1]])}")
print(f"固有値の和:{np.sum(L)}")
print(f"行列Aのトレース(対角成分の和):{np.sum(np.diag(A))}")
print(f"固有値の積:{np.prod(L)}")
print(f"行列Aの行列式:{np.linalg.det(A):.1f}")
print(f"行列Vの逆行列:{np.linalg.inv(V)}")
print(f"行列Vの転置:{V.T}")

行列Aの固有値:[4. 2.]
行列Aの固有ベクトル:[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
固有ベクトルの内積:[[0.]]
固有値の和:6.0
行列Aのトレース(対角成分の和):6
固有値の積:8.0
行列Aの行列式:8.0
行列Vの逆行列:[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
行列Vの転置:[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [20]:
A = np.array([[2, -3], [4, 1]])
b = np.array([[5], [-2]])
if np.linalg.det(A) != 0:
    w = np.matmul(np.linalg.inv(A), b)
    print(f"wの解) {w}")
else:
    print(f"解が存在しません")

wの解) [[-0.07142857]
 [-1.71428571]]


In [2]:
alpha = 0.2
w = 1
for ite in range(50):
    print(f"反復:{ite}, w = {round(w, 2):.2f}")
    w -= alpha * 3 * w**2

反復:0, w = 1.00
反復:1, w = 0.40
反復:2, w = 0.30
反復:3, w = 0.25
反復:4, w = 0.21
反復:5, w = 0.18
反復:6, w = 0.16
反復:7, w = 0.15
反復:8, w = 0.13
反復:9, w = 0.12
反復:10, w = 0.11
反復:11, w = 0.11
反復:12, w = 0.10
反復:13, w = 0.09
反復:14, w = 0.09
反復:15, w = 0.08
反復:16, w = 0.08
反復:17, w = 0.08
反復:18, w = 0.07
反復:19, w = 0.07
反復:20, w = 0.07
反復:21, w = 0.06
反復:22, w = 0.06
反復:23, w = 0.06
反復:24, w = 0.06
反復:25, w = 0.06
反復:26, w = 0.05
反復:27, w = 0.05
反復:28, w = 0.05
反復:29, w = 0.05
反復:30, w = 0.05
反復:31, w = 0.05
反復:32, w = 0.04
反復:33, w = 0.04
反復:34, w = 0.04
反復:35, w = 0.04
反復:36, w = 0.04
反復:37, w = 0.04
反復:38, w = 0.04
反復:39, w = 0.04
反復:40, w = 0.04
反復:41, w = 0.04
反復:42, w = 0.03
反復:43, w = 0.03
反復:44, w = 0.03
反復:45, w = 0.03
反復:46, w = 0.03
反復:47, w = 0.03
反復:48, w = 0.03
反復:49, w = 0.03


In [3]:
x1 = np.random.binomial(1, 6/13, 10)
x2 = np.random.binomial(1, 6/13, 10)
x3 = np.random.binomial(1, 6/13, 10)

print(f"データx1:{x1}")
print(f"データx1:{x2}")
print(f"データx1:{x3}")

データx1:[1 0 1 0 1 0 0 1 0 1]
データx1:[1 0 1 0 1 1 1 1 0 0]
データx1:[0 0 1 0 0 0 0 0 0 0]


箱の中にボールが13個入っている。そのうち青いボールは6個、赤いボールは7個  
青いボールのうち、木製は4個でゴム製は3個、赤いボールのうち、木製は3個でゴム製は4個 (箱の中に木製は7個、ゴム製は6個)  
ボールの色を確率変数x, ボールの材質を確率変数yとする  
ボールを1個取り出す。  
ボールを取り出した時、「木」かつ「青」→同時確率  
取り出したボールが木製であることがわかっていて、そのボールが「青」→条件付き確率 (材質の確率変数yは原因、色の確率変数xは結果)  
同時確率がわかっている状況から確率変数xの確率を求める方法：周辺化(確率変数が二つの場合は求める確率変数以外の変数をシグマする)  
同時確率は条件付き確率と周辺確率の積として表すことが可能 (乗法定理)  
乗法定理より、条件付き確率は同時確率を周辺確率で割ったものから求めることが可能   


In [14]:
x1 = np.random.normal(0, 1, 100)
x2 = np.random.normal(3, 1, 10)
x3 = np.random.normal(-3, 1, 10)

x1_list = x1.tolist()
in_std = []
out_std = []
for i in x1_list:
    if i <= 2 and i >= -2:
        in_std.append(i)
    else:
        out_std.append(i)
a = len(in_std)
b = len(out_std)
print(f"in_std:{a}")
print(f"out_std:{b}")

in_std:97
out_std:3
